name: Lint

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
    lint_python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
              with:
                  persist-credentials: false
            - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
            - name: Install Poetry
              uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Install dependencies
              run: poetry install --with dev --extras "cpu cli"
            - run: poetry run mypy --install-types --non-interactive --ignore-missing-imports ./rembg
            - run: poetry run bandit --recursive --skip B101,B104,B310,B311,B303,B110 --exclude ./rembg/_version.py ./rembg
            - run: poetry run black --force-exclude rembg/_version.py --check --diff ./rembg
            - run: poetry run flake8 ./rembg --count --ignore=B008,C901,E203,E266,E731,F401,F811,F841,W503,E501,E402 --show-source --statistics --exclude ./rembg/_version.py
            - run: poetry run isort --check-only --profile black ./rembg
